name: keli_client
description: End-user proxy client for the Keli/Xboardpro stack.
publish_to: "none"
version: 0.1.17+22

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
